spring:
  application:
    name: macos-demo
server:
  port: 8888
  random: 3600
mubbo:
  use: true
  config:
    client:
      macosBrokers: 140.143.184.197:10000,58.87.80.94:10000,129.204.169.119:10000
    server:
      host: 58.87.80.94
      macosNodes: 140.143.184.197:10000,58.87.80.94:10000,129.204.169.119:10000
netty:
  server:
    listenPort: 9000
    serverWorkerThreads: 8
    serverCallbackExecutorThreads: 0
    serverSelectorThreads: 3
    serverOnewaySemaphoreValue: 256
    serverAsyncSemaphoreValue: 64
    serverChannelMaxIdleTimeSeconds: 30
    serverSocketSndBufSize: 65535
    serverSocketRcvBufSize: 65535
    serverPooledByteBufAllocatorEnable: true
    useEpollNativeSelector: false
  client:
    clientWorkerThreads: 4
    clientOnewaySemaphoreValue: 65535
    clientAsyncSemaphoreValue: 65535
    connectTimeoutMillis: 3000
    channelNotActiveInterval: 60000
    clientChannelMaxIdleTimeSeconds: 30
    clientSocketSndBufSize: 65535
    clientSocketRcvBufSize: 65535
    clientPooledByteBufAllocatorEnable: true
    clientCloseSocketIfTimeout: true
    useTLS: false