spring:
  application:
    name: macos-broker
macos:
  broker:
    mode: CLUSTER
    host: 127.0.0.1  # 本机host
    clusterNodes: 127.0.0.1:10001,127.0.0.1:10002 # 集群节点列表
    servicePubNotify: false # 有新的服务发布时是否通知订阅者
  server:
    listenPort: 10000 # server端监听端口
    serverWorkerThreads: 8
    serverCallbackExecutorThreads: 0
    serverSelectorThreads: 3
    serverOnewaySemaphoreValue: 256
    serverAsyncSemaphoreValue: 64
    serverChannelMaxIdleTimeSeconds: 120
    serverSocketSndBufSize: 65535
    serverSocketRcvBufSize: 65535
    serverPooledByteBufAllocatorEnable: true
    useEpollNativeSelector: false
  # client for communicating with other brokers
  client:
    clientWorkerThreads: 4
    clientOnewaySemaphoreValue: 65535
    clientAsyncSemaphoreValue: 65535
    connectTimeoutMillis: 3000
    channelNotActiveInterval: 60000
    clientChannelMaxIdleTimeSeconds: 120
    clientSocketSndBufSize: 65535
    clientSocketRcvBufSize: 65535
    clientPooledByteBufAllocatorEnable: true
    clientCloseSocketIfTimeout: true
    useTLS: false